### ISSUE TITLE
Would you say this method is overall better than IFRNet?

### ISSUE THREAD

**Issue by dillfrescott** [98mxr/GMFSS_union#6]
https://github.com/ltkong218/IFRNet

Not sure if you would know but I guess it doesn't hurt to ask!

**Comment by 98mxr** [comment]
I cannot claim who is better in method, because these two networks are designed in different applicable scenarios.
Forcing one idea to be better is one-sided and reckless, and in essence, both models are Flow Base VFI

**Comment by jreoka** [comment]
Okay. I was just wondering which one to use for anime interpolation is all.

**Comment by 98mxr** [comment]
I have tried IFRNet and I think GMFSS has better subjective performance in most anime scenarios. (That would be very rigorous to say that)

**Comment by jreoka** [comment]
Noted. Thank you!
